"""Add version column for optimistic locking

Revision ID: 38dc3d92628d
Revises: f364386c3dc4
Create Date: 2026-06-15 03:00:40.015803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dc3d92628d'
down_revision: Union[str, None] = 'f364386c3dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'version')
    # ### end Alembic commands ###
